spring.application.name=belajar-kafka

kafka.bootstrap-servers=pkc-ew3qg.asia-southeast2.gcp.confluent.cloud:9092
kafka.security.protocol=SASL_SSL
kafka.sasl.mechanism=PLAIN
kafka.sasl.username=${CONFLUENT_CLOUD_API_KEY}
kafka.sasl.password=${CONFLUENT_CLOUD_API_SECRET}
kafka.topic=thermostat_readings
kafka.consumer-group-id=belajar-kafka-java
kafka.auto-offset-reset=earliest
kafka.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
kafka.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer
kafka.group-id=java

