spring.application.name=belajar-kafka

kafka.bootstrap-servers=localhost:9092
kafka.auto-offset-reset=earliest
kafka.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
kafka.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer
kafka.group-id=java

